### ISSUE TITLE
Simple Offline Viewer Bugs

### ISSUE THREAD

**Issue by kukreja-vikramaditya** [MobileApplicationsClub/DoJMA#14]
Added a new activity to show article data in offline mode...
Problems include - 
1. If user is downloading for first time description data is not downloaded with it so offline mode won't show anything useful
2. Also description downloading includes wrong extra data like "Leave a comment ... etc "

**Comment by hardik124** [comment]
@kukreja-vikramaditya can we just save all the images with a definite name , and if already exists in the sd card , it will display all images by loading from the card .
for example , both mess menu can be saved as , menu-a ,menu-c
There can be a prefix for every section ,and next 3-4 characters for the subsection , and so on , 
If this issue is still relevant , can i work on this?

**Comment by kukreja-vikramaditya** [comment]
@hardik124 
Currently images are downloaded using the Fresco library. Fresco uses caching to store images but it does have the option to get the bitmap. In order to solve this you need to find out a way to extract the bitmap and save it, as you suggested above, and then display it in the offline article loading activity.

**Comment by kukreja-vikramaditya** [comment]
All issues marked as `valid` can be worked on

**Comment by hardik124** [comment]
can we not switch to picasso ? 
by that , we can store the images as well.

Or we can use getImageEncoded of fresco library , and then use fileoutputstream to save it.

**Comment by kukreja-vikramaditya** [comment]
Please stick to Fresco. See http://stackoverflow.com/a/29567946/5262677 for more. Please send PR with your solution.

**Comment by hardik124** [comment]
Can you guide me more on this ?

**Comment by hardik124** [comment]
@kukreja-vikramaditya  , Can you please guide me more on this?
